# Generated by Django 4.2.4 on 2023-08-12 17:19

from django.db import migrations, models
import django.db.models.deletion
import invoice.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "number",
                    models.CharField(
                        default=invoice.models.generate_invoice_number, max_length=255
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("units", models.IntegerField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("amount", models.FloatField(default=0.0)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoice.invoice",
                    ),
                ),
            ],
        ),
    ]
